# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: cifar
  - /task: multiclass_classification
  - /optimizer: adamw
  - /scheduler: plateau

train:
  monitor: val/accuracy # Needed for plateau scheduler
  mode: max

encoder: linear

optimizer:
  lr: 0.0005 #0.0005
  weight_decay: 0.01

decoder:
  _name_: sequence
  mode: pool
